## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
googleAnalytics = "G-YY8FZQ9TE9"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
description = ""
logo = "images/banner.jpg"
favicon = false

[Params.social]
email = "ron.smith@ablecncrepairllc.com"

[Params.asset]
fontawesome_css = ["css/fontawesome-all.min.css"]
fontawesome_js = ["js/fontawesome-all.min.js"]
